---
title: "DA2 - Hotels Europe Analysis"
author: "Adam Kovacs, Nam Son Nguyen"
date: "12/04/2021"
output: 
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
---

## Introduction

In this project, we analyze the [**hotels-europe dataset**](https://osf.io/r6uqb/) to investigate how high rating is related to the other hotel features in the data. We estimate linear probability, logit, and probit models with distance and stars as explanatory variables. 

```{r import, echo=FALSE, message=FALSE}
#clear memory
rm(list=ls())

#import packages
if (!require(pacman)){
  install.packages("pacman")
}

pacman::p_load(tidyverse, modelsummary, kableExtra, fixest, estimatr, mfx)

# import data
hprices <- read_csv('https://osf.io/p6tyr/download')
hfeatures <- read_csv('https://osf.io/utwjs/download')

#table(hfeatures$city)

```

## Filtering for city

```{r filter, echo=FALSE}
#merge the two datasets
hotels <- merge(hprices, hfeatures)
#filter on London and create binary variable highly_rated
london <- hotels %>% filter(city_actual == "London") %>% 
                     mutate(highly_rated = ifelse(rating >= 4, 1, 0))

```

## Descriptive statistics


```{r descriptives, echo=FALSE}

#create 5th and 95th percentiles

P95 <- function(x){quantile(x,0.95,na.rm=T)}
P05 <- function(x){quantile(x,0.05,na.rm=T)}

#create descriptive table
datasummary( (`Highly rated` = highly_rated ) + (`Distance from center` = distance ) + 
               (`Stars` = stars ) ~
               Mean + Median + SD + Min + Max + P05 + P95, 
             data = london,
             title = 'Descriptive stats of main variables' ) %>% 
  kableExtra::kable_styling(latex_options = "hold_position")

```

## Regressions

```{r, echo=FALSE}
#assess accomodation type as other explanatory variable
unique(london$accommodation_type)
#linear probability model
lpm <- feols(highly_rated ~ distance + stars + as.factor(accommodation_type), data=london, vcov = 'hetero')
#logit model
logit <- glm(highly_rated ~ distance + stars + as.factor(accommodation_type), data=london, family = "binomial")
#logit model marginal effects
logitm <- logitmfx(highly_rated ~ distance + stars + as.factor(accommodation_type), data=london, atmean = F, robust = T)
#probit model
probit <- glm(highly_rated ~ distance + stars + as.factor(accommodation_type), data=london, family = binomial(link = "probit"))
#probit model marginal effects
probitm <- probitmfx(highly_rated ~ distance + stars + as.factor(accommodation_type), data=london, atmean = F, robust = T)
#summary of models
msummary(list("LPM" = lpm, "Logit" = logit, "Logit_marginal" = logitm, "Probit" =  probit, "Probit_marginal" = probitm),
         fmt="%.2f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|R2 Within|R2 Pseudo|R2',
         stars=c('*' = .05, '**' = .01),
         estimate = "{estimate} ({std.error}){stars}",
         statistic = NULL,
         coef_rename = c("distance" = "Distance",
                         "stars" = "Stars",
                         "as.factor(accommodation_type)Apartment" = "High school graduate",
                         "as.factor(accommodation_type)Bed and breakfast" = "College no degree",
                         "as.factor(accommodation_type)Guest House" = "Guest House",
                         "as.factor(accommodation_type)Hostel" = "Hostel",
                         "as.factor(accommodation_type)Hotel" = "Hotel",
                         "as.factor(accommodation_type)Inn" = "Inn"),
         title = "Highly rated") %>% 
        column_spec(1:6, width = "7em") %>%
        kable_classic(full_width = F, position = "center" )

```
## Conclusion
